<div class="field field-linkedin_profile" style="margin: 0; padding: 0;">
    <label class="label" for="linkedin_profile" style="display: block; text-align: left; margin-bottom: 5px;">
        <span><?= __('LinkedIn Profile') ?></span>
    </label>
    <div class="control" style="padding: 0;">
        <input
            type="text"
            id="linkedin_profile"
            name="linkedin_profile"
            class="input-text"
            data-validate='{"required":true, "validate-url":true}'
            maxlength="250"
            style="width: 100%; max-width: 600px; margin-left: 0;"/>
    </div>
</div>
